include_recipe 'pivotal_workstation::1password'
include_recipe 'pivotal_workstation::pg_admin'
include_recipe 'pivotal_workstation::libreoffice'
include_recipe 'apps::fitbit'
include_recipe 'apps::rdio'