maintainer        'Abhijit Hiremagalur'
maintainer_email  'abhijit@hiremaga.com'
license           'MIT'
description       'Installs tools Abhi has come to rely on for development'
version           '0.1'
supports          'mac_os_x'
depends           'pivotal_workstation'
depends           'apps'

recipe 'workstation::git_config', 'Tell Git about Abhi'
recipe 'workstation::apps', 'Installs various packages'
recipe 'workstation::packages', 'Installs various applications'